@extends('layout')
@section('page_title','انتشار محتوا')
@section('page_hint','محتوا را انتخاب کن، زمان انتشار را مشخص کن و منتشر کن')
@section('content')
<form method="POST" action="{{ route('content.store') }}" id="contentCreateForm" class="content-create-shell">
@csrf
<input type="hidden" name="media_items_json" id="mediaItemsJson">
<input type="hidden" name="user_tags_json" id="userTagsJson">
<div class="page-header-row"><div><a class="back-link" href="{{ route('content') }}">← محتوا</a><div class="eyebrow">انتشار جدید</div><h1>انتشار محتوا</h1><p>رسانه و زمان انتشار را مشخص کن.</p></div><button class="primary-action" type="submit">✓ ذخیره و انتشار</button></div>
<div class="content-create-grid">
<div class="content-main-column">
<section class="editor-card"><div class="section-head"><div><div class="eyebrow">۱ • حساب و نوع محتوا</div><h2>از کدام حساب و چه فرمتی؟</h2></div></div>
<div class="account-grid compact-account">@foreach($accounts as $account)<label class="account-choice {{ $loop->first?'selected':'' }}"><input type="radio" name="account_id" value="{{ $account->id }}" {{ $loop->first?'checked':'' }}><span class="account-avatar">{{ mb_strtoupper(mb_substr($account->username ?: 'IG',0,2)) }}</span><span class="account-copy"><strong>{{ '@'.($account->username ?: 'instagram') }}</strong><span>{{ $account->name ?: 'حساب فعال' }}</span></span><i>✓</i></label>@endforeach</div>
<div class="publish-type-grid" data-content-type-picker><label class="publish-type-card selected"><input type="radio" name="content_type" value="feed" checked><span>▧</span><strong>پست</strong><small>تصویر یا ویدیو</small></label><label class="publish-type-card"><input type="radio" name="content_type" value="carousel"><span>▤</span><strong>آلبوم</strong><small>۲ تا ۱۰ رسانه</small></label><label class="publish-type-card"><input type="radio" name="content_type" value="reel"><span>◉</span><strong>ریلز</strong><small>ویدیو عمودی</small></label><label class="publish-type-card"><input type="radio" name="content_type" value="story"><span>◌</span><strong>استوری</strong><small>تا ۲۴ ساعت</small></label></div>
</section>

<section class="editor-card"><div class="section-head"><div><div class="eyebrow">۲ • رسانه</div><h2>فایل‌ها را اینجا انتخاب کن</h2><p>می‌توانی چند تصویر یا ویدیو برای آلبوم انتخاب کنی.</p></div><span class="soft-tag">حداکثر ۱۰ فایل</span></div>
<div class="upload-dropzone" data-content-upload-zone><input type="file" id="contentMediaUpload" multiple hidden accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,video/webm"><button type="button" class="upload-drop-button" data-content-upload><span>↑</span><strong>افزودن رسانه</strong><small>تصاویر PNG/JPG تا ۸MB • ویدیو برای انتشار طبق محدودیت پلتفرم</small></button></div><div class="selected-media-list" id="contentSelectedMedia"><div class="empty-mini">هنوز رسانه‌ای انتخاب نشده.</div></div>
</section>

<section class="editor-card"><div class="section-head"><div><div class="eyebrow">۳ • متن</div><h2>کپشن را بنویس</h2></div><span class="char-counter" data-counter-for="#contentCaption">۰ / ۲۲۰۰</span></div><div class="message-editor"><textarea id="contentCaption" name="caption" maxlength="2200" placeholder="متن کپشن…"></textarea></div><div class="form-grid"><div class="form-field"><label>اولین کامنت <span class="muted">اختیاری</span></label><textarea name="first_comment" maxlength="2200" placeholder="لینک یا توضیح تکمیلی…"></textarea></div><div class="form-field"><label>همکاران <span class="muted">حداکثر ۳ نفر</span></label><input name="collaborators" placeholder="نام‌های کاربری با ویرگول"></div></div></section>

<section class="editor-card"><details class="advanced-wrap" open><summary><span><b>تنظیمات انتشار</b><small>زمان‌بندی، صدا، جلد ریلز و گزینه‌های بیشتر</small></span><b>⌄</b></summary><div class="advanced-body">
<div class="publish-mode-tabs"><label class="publish-mode active"><input type="radio" name="publish_mode" value="now" checked><b>اکنون</b><span>بلافاصله منتشر شود</span></label><label class="publish-mode"><input type="radio" name="publish_mode" value="scheduled"><b>زمان‌بندی</b><span>انتشار در تاریخ و ساعت انتخابی</span></label><label class="publish-mode"><input type="radio" name="publish_mode" value="draft"><b>پیش‌نویس</b><span>فعلاً منتشر نشود</span></label></div>
<input type="hidden" name="timezone" value="Asia/Tehran" id="hiddenTimezone"><div class="schedule-row" id="scheduleRow" hidden><div class="form-field"><label>تاریخ و ساعت</label><input type="datetime-local" name="scheduled_at"></div><div class="form-field"><label>منطقه زمانی</label><input data-timezone-visible value="Asia/Tehran"></div></div>
<div class="grid-three"><label class="toggle-row"><span><strong>فعال‌بودن نظرات</strong><small>بعد از انتشار قابل تغییر است.</small></span><input class="toggle-input" name="comments_enabled" value="1" type="checkbox" checked><span class="toggle-ui"></span></label><label class="toggle-row reel-only"><span><strong>نمایش در فید</strong><small>برای ریلز.</small></span><input class="toggle-input" name="share_to_feed" value="1" type="checkbox" checked><span class="toggle-ui"></span></label><label class="toggle-row video-only"><span><strong>بی‌صدا</strong><small>صدای ویدیو حذف شود.</small></span><input class="toggle-input" name="mute_audio" value="1" type="checkbox"><span class="toggle-ui"></span></label></div>
<div class="audio-picker-card reel-only"><div class="audio-picker-head"><div><strong>صدای اینستاگرام</strong><small>برای ریلز می‌توانی از صداهای حساب استفاده کنی.</small></div><button type="button" class="ghost-action" data-audio-load>بارگذاری صداها</button></div><div class="audio-list" data-audio-list><div class="empty-mini">هنوز صدایی انتخاب نشده.</div></div><input type="hidden" name="audio_id" id="audioId"><div class="grid-three"><div class="quick-input-wrap"><label>بلندی صدای اصلی</label><input name="video_volume" type="number" min="0" max="100" value="100"></div><div class="quick-input-wrap"><label>بلندی صدای انتخابی</label><input name="audio_volume" type="number" min="0" max="100" value="100"></div><div class="quick-input-wrap"><label>استراتژی Trial Reel</label><select name="trial_strategy"><option value="">بدون Trial</option><option value="MANUAL">دستی</option><option value="SS_PERFORMANCE">بر اساس عملکرد</option></select></div></div></div>
<div class="form-grid reel-only"><div class="form-field"><label>عنوان ریلز <span class="muted">اختیاری</span></label><input name="reel_title" maxlength="90" placeholder="عنوان کوتاه برای ریلز"></div><div class="form-field"><label>لینک جلد ریلز <span class="muted">اختیاری</span></label><input name="reel_cover_url" type="url" placeholder="https://..."></div><div class="form-field"><label>جابجایی جلد (میلی‌ثانیه)</label><input name="thumb_offset" type="number" min="0" value="0"></div></div>
<div class="form-grid"><div class="form-field"><label>همکاری تبلیغاتی <span class="muted">اختیاری</span></label><label class="toggle-row inline-toggle"><span><strong>برچسب همکاری تجاری</strong></span><input class="toggle-input" name="is_paid_partnership" value="1" type="checkbox"><span class="toggle-ui"></span></label><input name="branded_content_sponsors" placeholder="حساب همکار، با ویرگول"></div><div class="form-field"><label>موقعیت <span class="muted">شناسه صفحه</span></label><input name="location_id" placeholder="اختیاری"></div></div><div class="form-grid"><div class="form-field"><label>برچسب‌گذاری افراد <span class="muted">اختیاری</span></label><input id="userTagsText" placeholder="username1, username2"><small class="field-note">نام کاربری افراد را با ویرگول جدا کن.</small></div><div class="form-field"><label>نام صدا <span class="muted">برای ریلز</span></label><input name="audio_name" maxlength="200" placeholder="در صورت نیاز"></div></div>
<label class="toggle-row"><span><strong>برچسب محتوای تولیدشده با هوش مصنوعی</strong><small>فقط برای نشانه‌گذاری محتوای بصری.</small></span><input class="toggle-input" name="is_ai_generated" value="1" type="checkbox"><span class="toggle-ui"></span></label>
</div></details></section>
</div>

<aside class="content-create-side sticky-side"><section class="studio-preview-card"><div class="studio-preview-head"><div><span class="eyebrow">پیش‌نمایش</span><strong>چطور دیده می‌شود</strong></div><span class="live-pill"><i></i> زنده</span></div><div class="ig-preview"><div class="ig-preview-head"><div class="avatar">IG</div><div><b>{{ '@'.($selected?->username ?? 'instagram') }}</b><small>اکنون</small></div><span>•••</span></div><div class="ig-preview-media" id="contentPreviewMedia"><div class="preview-media-empty">رسانه را انتخاب کن</div></div><div class="ig-preview-body"><div class="ig-actions">♡ &nbsp;♡ &nbsp;⌁ <span>↗</span></div><p id="contentPreviewCaption">کپشن اینجا نمایش داده می‌شود.</p></div></div></section><section class="preview-card"><div class="preview-head"><strong>چک‌لیست</strong><span>۳ مورد</span></div><div class="check-list"><div class="check-item" data-check="account">✓ <span>حساب انتخاب شده</span></div><div class="check-item" data-check="media">○ <span>حداقل یک رسانه</span></div><div class="check-item" data-check="type">✓ <span>نوع محتوا مشخص است</span></div></div></section></aside>
</div>
</form>
@endsection
