@extends('layout')
@section('page_title','ویرایش اتوماسیون')
@section('page_hint','تغییرات را سریع ذخیره کن؛ نسخه قبلی برایت نگهداری می‌شود')
@php
    $statusLabels=['active'=>'فعال','paused'=>'متوقف','draft'=>'پیش‌نویس'];
    $trigger = $automation->trigger instanceof \BackedEnum ? $automation->trigger->value : (string)$automation->trigger;
    $triggerLabels=['comment'=>'نظر روی پست','story_reply'=>'پاسخ استوری','direct_message'=>'پیام مستقیم'];
    $actionPublic=$automation->actions->firstWhere('action','public_reply');
    $actionReply=$automation->actions->firstWhere(fn($a)=>in_array($a->action,['private_reply','direct_message'],true));
    $actionConfig=$actionReply?->config ?? [];
    $quickReplies=$actionConfig['quickReplies'] ?? [];
    $buttons=$actionConfig['buttons'] ?? [];
    $template=$actionConfig['template'] ?? [];
    $isPublic=$trigger==='comment' && !$automation->actions->contains('action','private_reply');
@endphp
@section('content')
<div class="edit-hero">
    <div class="edit-identity"><a class="back-link" href="{{ route('automations.index') }}">← اتوماسیون‌ها</a><div class="edit-title-row"><div class="flow-avatar xlarge">{{ $trigger==='comment'?'◎':($trigger==='story_reply'?'◌':'↗') }}</div><div><div class="eyebrow">ویرایش گردش‌کار</div><h1>{{ $automation->name }}</h1><p>{{ $automation->account?->username ? '@'.$automation->account->username.' • ' : '' }}{{ $triggerLabels[$trigger] ?? $trigger }}</p></div></div></div>
    <div class="edit-top-actions"><span class="status-badge {{ $automation->status }}"><i></i>{{ $statusLabels[$automation->status] ?? $automation->status }}</span><form method="POST" action="{{ route('automations.toggle',$automation) }}">@csrf<button class="secondary-action" type="submit">{{ $automation->status==='active'?'متوقف‌کردن':'فعال‌کردن' }}</button></form><button class="danger-action soft-danger" type="button" data-confirm-form="delete-edit-{{ $automation->id }}" data-confirm-title="حذف اتوماسیون" data-confirm-text="این اتوماسیون برای همیشه حذف می‌شود.">حذف</button><form id="delete-edit-{{ $automation->id }}" method="POST" action="{{ route('automations.destroy',$automation) }}" hidden>@csrf @method('DELETE')</form></div>
</div>

<form method="POST" action="{{ route('automations.update',$automation) }}" class="editor-layout" id="automationEditForm" data-trigger="{{ $trigger }}" data-public="{{ $isPublic ? "1" : "0" }}">
@csrf @method('PUT')
<input type="hidden" name="execution_mode" id="editExecutionMode" value="zernio">
<input type="hidden" name="goal" value="{{ $isPublic ? 'comment_public' : 'comment_dm' }}">
<input type="hidden" name="also_match_in_dms" id="editAlsoDms" value="{{ data_get($automation->settings,'alsoMatchInDms',false)?1:0 }}">
<input type="hidden" name="message_tag" id="editMessageTag" value="{{ $actionConfig['messageTag'] ?? '' }}">
<input type="hidden" name="link_preview" id="editLinkPreview" value="{{ !empty($actionConfig['linkPreview'])?1:0 }}">
<input type="hidden" name="quick_replies_json" id="editQuickJson" value="">
<input type="hidden" name="buttons_json" id="editButtonsJson" value="">
<input type="hidden" name="template_json" id="editTemplateJson" value='@json($template)'>

<div class="editor-main">
<section class="editor-card editor-card-main"><div class="section-head"><div><div class="eyebrow">اطلاعات پایه</div><h2>قانون را همان‌طور که اجرا می‌شود ببین</h2></div><span class="soft-tag">نسخه {{ $automation->versions()->max('version') }}</span></div>
<div class="flow-rail"><div class="flow-rail-item"><span>۱</span><strong>{{ $triggerLabels[$trigger] ?? $trigger }}</strong><small>محرک</small></div><b>→</b><div class="flow-rail-item"><span>۲</span><strong>{{ $automation->target_id ? ($automation->target_type==='story'?'یک استوری':'یک پست') : 'همه محتوا' }}</strong><small>هدف</small></div><b>→</b><div class="flow-rail-item"><span>۳</span><strong>{{ $automation->actions->count() }} اقدام</strong><small>عملیات</small></div></div>
<div class="form-grid"><div class="form-field"><label>نام اتوماسیون</label><input name="name" required maxlength="120" value="{{ $automation->name }}"></div><div class="form-field"><label>وضعیت</label><select name="status"><option value="active" @selected($automation->status==='active')>فعال</option><option value="paused" @selected($automation->status==='paused')>متوقف</option><option value="draft" @selected($automation->status==='draft')>پیش‌نویس</option></select></div><div class="form-field full"><label>یادداشت داخلی</label><input name="description" maxlength="1000" value="{{ $automation->description }}" placeholder="مثلاً مربوط به کمپین پاییز"></div></div>
</section>

<section class="editor-card"><div class="section-head"><div><div class="eyebrow">محتوا</div><h2>شرط و متن پاسخ</h2><p>مقادیر اصلی را همین‌جا تغییر بده؛ نتیجه در پیش‌نمایش سمت راست دیده می‌شود.</p></div></div>
<div class="form-grid"><div class="form-field full"><label>کلمات فعال‌کننده</label><input name="keywords" value="{{ $automation->keywords->where('is_excluded',false)->pluck('keyword')->implode(', ') }}" placeholder="قیمت، سفارش، خرید"></div><div class="form-field full"><label>کلمات استثنا</label><input name="excluded_keywords" value="{{ $automation->keywords->where('is_excluded',true)->pluck('keyword')->implode(', ') }}"></div>
<div class="form-field full"><label>پاسخ عمومی <span class="muted">اختیاری</span></label><textarea name="public_reply" maxlength="2200" id="editPublicReply">{{ $actionPublic?->config['message'] ?? '' }}</textarea></div>
<div class="form-field full"><label>{{ $trigger==='comment' && !$isPublic?'پیام خصوصی':($trigger==='comment'?'پاسخ خصوصی':'پیام مستقیم') }}</label><div class="message-editor"><textarea name="{{ $trigger==='comment' ? 'private_reply':'dm_message' }}" id="editMessage" maxlength="10000" placeholder="سلام @{{username}}، پیام شما دریافت شد…">{{ $actionReply?->config['message'] ?? '' }}</textarea><div class="editor-foot"><div class="token-row"><button type="button" class="token-chip" data-insert-target="#editMessage" data-insert-token="@{{username}}">نام کاربر</button><button type="button" class="token-chip" data-insert-target="#editMessage" data-insert-token="@{{comment}}">متن ورودی</button><button type="button" class="token-chip" data-insert-target="#editMessage" data-insert-token="@{{post_url}}">لینک پست</button></div><span class="char-counter" data-counter-for="#editMessage"></span></div></div>
@include('partials.message_attachment_composer',['prefix'=>'dm','automationTrigger'=>$trigger,'attachmentUrl'=>$actionConfig['attachmentUrl'] ?? '','attachmentType'=>$actionConfig['attachmentType'] ?? '','attachmentName'=>$actionConfig['attachmentName'] ?? '','sequence'=>$automation->actions->where('action','direct_message')->sortBy('sort_order')->map(fn($action)=>array_merge(['type'=>!empty($action->config['attachmentUrl'])?'media':'text','message'=>$action->config['message'] ?? ''],!empty($action->config['attachmentUrl'])?['attachmentUrl'=>$action->config['attachmentUrl'],'attachmentType'=>$action->config['attachmentType'] ?? 'file','attachmentName'=>$action->config['attachmentName'] ?? '']:[]))->values()->all()])
</div></div></section>
<div class="follow-gate-card" id="editFollowGateCard" @if(!($trigger==='comment' && !$isPublic)) hidden @endif data-enabled="{{ data_get($automation->settings,'followGateEnabled',false)?'1':'0' }}">
    <div class="follow-gate-head"><div><span class="eyebrow">شرط دنبال‌کردن</span><strong>قبل از ارسال پیام اصلی، دنبال‌کردن صفحه را بررسی کن</strong><p>این مرحله فقط برای پیام خصوصی کامنت استفاده می‌شود.</p></div><label class="toggle-row follow-gate-toggle"><span><strong>فعال باشد</strong><small>پیام اصلی فقط پس از تأیید دنبال‌کردن</small></span><input class="toggle-input" type="checkbox" name="follow_gate_enabled" value="1" id="editFollowGateEnabled" @checked(data_get($automation->settings,'followGateEnabled',false))><span class="toggle-ui"></span></label></div>
    <div class="follow-gate-flow"><span>کامنت</span><b>→</b><span>پیام راهنما</span><b>→</b><span>بررسی دنبال‌کردن</span><b>→</b><span>پیام اصلی</span></div>
    <div class="follow-gate-fields"><div class="form-field"><label>پیام قبل از بررسی</label><textarea name="follow_gate_message" id="editFollowGateMessage" maxlength="640">{{ data_get($automation->settings,'followGate.message','لطفاً ابتدا صفحه را دنبال کنید و سپس روی «بررسی کردم» بزنید.') }}</textarea></div><div class="form-field"><label>متن دکمه</label><input name="follow_gate_button_label" id="editFollowGateButtonLabel" maxlength="20" value="{{ data_get($automation->settings,'followGate.buttonLabel','بررسی کردم') }}"></div><div class="form-field full"><label>پیام اگر هنوز دنبال نکرده بود</label><textarea name="follow_gate_not_following_message" id="editFollowGateNotFollowingMessage" maxlength="640">{{ data_get($automation->settings,'followGate.notFollowingMessage','بعد از دنبال‌کردن صفحه، دوباره بررسی کنید.') }}</textarea></div></div>
    <div class="follow-gate-preview"><div class="follow-gate-preview-top"><span class="preview-avatar">IG</span><div><strong>صفحه شما</strong><small>پیام خودکار</small></div></div><div class="follow-gate-preview-bubble" id="editFollowGatePreviewMessage">{{ data_get($automation->settings,'followGate.message','لطفاً ابتدا صفحه را دنبال کنید و سپس روی «بررسی کردم» بزنید.') }}</div><button type="button" class="follow-gate-preview-button" id="editFollowGatePreviewButton">{{ data_get($automation->settings,'followGate.buttonLabel','بررسی کردم') }}</button><small class="follow-gate-preview-note">این مرحله قبل از پیام اصلی اجرا می‌شود.</small></div>
</div>

<section class="editor-card"><div class="section-head"><div><div class="eyebrow">پیام‌های تعاملی</div><h2>دکمه و پاسخ سریع</h2><p>برای پیام خصوصی یا دایرکت، عناصر تعاملی را با چند کلیک اضافه کن.</p></div></div>
<div class="form-field"><label>پاسخ‌های سریع</label><div class="repeater" data-repeater="quick">@foreach($quickReplies as $q)<div class="repeater-row"><input data-field="title" value="{{ $q['title'] ?? $q['content_type'] ?? '' }}"><button type="button" class="repeater-remove">×</button></div>@endforeach</div><button type="button" class="secondary-action" data-repeater-add="quick">＋ افزودن پاسخ سریع</button></div>
@include('partials.automation_button_builder', ['builderId'=>'editButtonBuilder','buttons'=>$buttons,'accountId'=>$automation->instagram_account_id])
</section>

<section class="editor-card"><details class="advanced-wrap" open><summary><span><b>تنظیمات پیشرفته</b><small>مخاطب، محدودیت، ساعات کاری، مسیرهای جایگزین</small></span><b>⌄</b></summary><div class="advanced-body">
<div class="grid-three"><div class="quick-input-wrap"><label>روش تطبیق</label><select name="match_mode"><option value="any" @selected(($automation->settings['matchMode'] ?? 'any') === 'any')>هر واژه</option><option value="all" @selected(($automation->settings['matchMode']??'any')==='all')>همه واژه‌ها</option><option value="contains" @selected(($automation->settings['matchMode']??'any')==='contains')>شامل عبارت</option><option value="exact" @selected(($automation->settings['matchMode']??'any')==='exact')>تطبیق دقیق</option><option value="word" @selected(($automation->settings['matchMode']??'any')==='word')>تطبیق کلمه</option></select></div><div class="quick-input-wrap"><label>مخاطب</label><select name="audience_follower_status"><option value="any" @selected(data_get($automation->audience,'followerStatus','any')==='any')>همه</option><option value="follower" @selected(data_get($automation->audience,'followerStatus')==='follower')>دنبال‌کننده</option><option value="non_follower" @selected(data_get($automation->audience,'followerStatus')==='non_follower')>غیردنبال‌کننده</option></select></div><div class="quick-input-wrap"><label>حداقل دنبال‌کننده</label><input name="min_follower_count" type="number" min="0" value="{{ data_get($automation->audience,'minFollowerCount') }}"></div></div>
<div class="grid-three"><div class="quick-input-wrap"><label>اولویت</label><input name="priority" type="number" min="1" max="9999" value="{{ $automation->priority }}"></div><div class="quick-input-wrap"><label>وقفه پاسخ</label><input name="cooldown_seconds" type="number" min="0" max="86400" value="{{ $automation->cooldown_seconds }}"></div><div class="quick-input-wrap"><label>حداکثر پاسخ روزانه</label><input name="max_per_user_day" type="number" min="1" max="10000" value="{{ $automation->max_per_user_day }}"></div></div>
<div class="grid-three"><div class="quick-input-wrap"><label>تأخیر پیام خصوصی</label><input name="dm_delay_seconds" type="number" min="0" max="86400" value="{{ data_get($automation->settings,'dmDelaySeconds',0) }}"></div><div class="quick-input-wrap"><label>تأخیر پاسخ عمومی</label><input name="comment_reply_delay_seconds" type="number" min="0" max="86400" value="{{ data_get($automation->settings,'commentReplyDelaySeconds',0) }}"></div><div class="quick-input-wrap"><label>رفتار مخاطب نامشخص</label><select name="audience_unknown"><option value="send" @selected(data_get($automation->audience,'whenUnknown','send')==='send')>ارسال</option><option value="skip" @selected(data_get($automation->audience,'whenUnknown')==='skip')>صرف‌نظر</option><option value="verify" @selected(data_get($automation->audience,'whenUnknown')==='verify')>بررسی</option></select></div></div>
<div class="advanced-toggle-grid"><label class="toggle-row"><span><strong>فقط ساعات کاری</strong><small>از تنظیمات اصلی استفاده می‌کند.</small></span><input class="toggle-input" type="checkbox" name="business_hours_only" value="1" @checked($automation->business_hours_only)><span class="toggle-ui"></span></label><label class="toggle-row"><span><strong>تحویل به اپراتور</strong><small>گفتگو برای پیگیری علامت بخورد.</small></span><input class="toggle-input" type="checkbox" name="handoff_enabled" value="1" @checked($automation->handoff_enabled)><span class="toggle-ui"></span></label><label class="toggle-row"><span><strong>بررسی در دایرکت</strong><small>همین واژه‌ها را در DM هم بررسی کن.</small></span><input class="toggle-input" type="checkbox" name="also_match_in_dms" value="1" @checked(data_get($automation->settings,'alsoMatchInDms',false))><span class="toggle-ui"></span></label><label class="toggle-row"><span><strong>ردیابی لینک</strong><small>لینک‌های پاسخ را قابل رهگیری می‌کند.</small></span><input class="toggle-input" type="checkbox" name="link_tracking" value="1" @checked(data_get($automation->settings,'linkTracking',false))><span class="toggle-ui"></span></label></div>
<div class="grid-three"><div class="quick-input-wrap"><label>برچسب پیام</label><select name="message_tag"><option value="" @selected(empty($actionConfig['messageTag']))>بدون برچسب</option><option value="HUMAN_AGENT" @selected(($actionConfig['messageTag']??'')==='HUMAN_AGENT')>پیگیری انسانی</option></select></div><div class="quick-input-wrap"><label>پیش‌نمایش لینک</label><select name="link_preview"><option value="0" @selected(empty($actionConfig['linkPreview']))>خاموش</option><option value="1" @selected(!empty($actionConfig['linkPreview']))>روشن</option></select></div><div class="quick-input-wrap"><label>برچسب مخاطب</label><input name="add_tag" value="{{ data_get($automation->actions->firstWhere('action','add_tag'),'config.tag','') }}" placeholder="مثلاً مشتری جدید"></div></div>
<div class="form-field full"><label>پاسخ‌های جایگزین</label><textarea name="variations">{{ collect(data_get($automation->settings,'dmMessageVariations',[]))->implode("\n") }}</textarea></div>
<label class="toggle-row"><span><strong>مخفی‌کردن کامنت</strong><small>پس از تشخیص، کامنت مخفی شود.</small></span><input class="toggle-input" type="checkbox" name="hide_comment" value="1" @checked($automation->actions->contains('action','hide_comment'))><span class="toggle-ui"></span></label>
<div class="form-field"><label>قالب کارت / چرخان</label><textarea name="template_input" id="editTemplateInput">@if($template){{ json_encode($template, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT) }}@endif</textarea></div>
</div></details></section>

<div class="save-dock"><div><span class="save-dot"></span><div><strong>همه تغییرات آماده ذخیره‌اند</strong><small>ذخیره، نسخه جدید اتوماسیون را ثبت می‌کند.</small></div></div><div class="save-dock-actions"><a class="secondary-action" href="{{ route('automations.index') }}">انصراف</a><button class="primary-action" type="submit">✓ ذخیره تغییرات</button></div></div>
</div>

<aside class="editor-side sticky-side">
<section class="studio-preview-card"><div class="studio-preview-head"><div><span class="eyebrow">پیش‌نمایش</span><strong>پیام در گفتگو</strong></div><span class="live-pill"><i></i> زنده</span></div><div class="phone-frame modern-phone"><div class="phone-screen"><div class="phone-bar"><span></span><b>پیام‌ها</b><span>⋮</span></div><div class="chat-profile"><div class="avatar">IG</div><div><strong>صفحه شما</strong><small>فعال</small></div></div><div class="chat-area"><div class="bubble incoming">قیمت این محصول چنده؟</div><div class="bubble outgoing" id="editPreview">{{ $actionReply?->config['message'] ?? 'متن پاسخ اینجا نمایش داده می‌شود.' }}</div></div><div class="chat-input">پیام… <span>⌁</span></div></div></div></section>
<section class="flow-summary-card"><div class="flow-card-title"><strong>وضعیت اجرا</strong><span>{{ $automation->runs_count ?? $automation->runs()->count() }} اجرا</span></div><div class="flow-stats"><div><b>{{ $automation->actions->count() }}</b><span>اقدام</span></div><div><b>{{ $automation->priority }}</b><span>اولویت</span></div><div><b>{{ $automation->cooldown_seconds }}s</b><span>وقفه</span></div></div></section>
<section class="preview-card"><div class="preview-head"><strong>شبیه‌سازی</strong><span class="soft-tag blue">بدون ارسال</span></div><textarea id="simTextEdit" class="inbox-message-input" style="min-height:90px">قیمت این محصول چنده؟</textarea><button class="secondary-action full-width" type="button" data-simulate="{{ $automation->id }}" data-sim-result="#simResultEdit">اجرای شبیه‌سازی</button><pre id="simResultEdit" class="help-box sim-output">نتیجه اینجا نمایش داده می‌شود.</pre></section>
</aside>
</form>
@endsection
