<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PanelController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\OperationsController;
Route::get('/login',[AuthController::class,'login'])->name('login');
Route::post('/login',[AuthController::class,'authenticate'])->name('login.authenticate');
Route::post('/logout',[AuthController::class,'logout'])->name('logout');
Route::middleware('panel.auth')->group(function(){
 Route::get('/',fn()=>redirect()->route('dashboard'));
 Route::get('/dashboard',[PanelController::class,'dashboard'])->name('dashboard');
 Route::get('/automations',[PanelController::class,'automations'])->name('automations.index');
 Route::get('/automations/create',[PanelController::class,'create'])->name('automations.create');
 Route::get('/automations/media',[PanelController::class,'media'])->name('automations.media');
 Route::get('/automations/workflows',[PanelController::class,'workflows'])->name('automations.workflows');
 Route::post('/automations/media/upload',[PanelController::class,'uploadMedia'])->name('automations.media.upload');
 Route::post('/automations',[PanelController::class,'store'])->name('automations.store');
 Route::get('/automations/{automation}/edit',[PanelController::class,'edit'])->name('automations.edit');
 Route::put('/automations/{automation}',[PanelController::class,'update'])->name('automations.update');
 Route::post('/automations/{automation}/toggle',[PanelController::class,'toggle'])->name('automations.toggle');
 Route::post('/automations/{automation}/simulate',[PanelController::class,'simulator'])->name('automations.simulate');
 Route::delete('/automations/{automation}',[PanelController::class,'destroy'])->name('automations.destroy');
 Route::get('/inbox',[PanelController::class,'inbox'])->name('inbox');
 Route::get('/inbox/{conversation}',[PanelController::class,'conversation'])->name('inbox.show');
 Route::post('/inbox/{conversation}/send',[PanelController::class,'sendMessage'])->name('inbox.send');
 Route::post('/inbox/{conversation}/human',[PanelController::class,'markHuman'])->name('inbox.human');
 Route::post('/inbox/{conversation}/archive',[PanelController::class,'archiveConversation'])->name('inbox.archive');
 Route::post('/inbox/{conversation}/messages/{message}/react',[PanelController::class,'reactMessage'])->name('inbox.message.react');
 Route::delete('/inbox/{conversation}/messages/{message}/react',[PanelController::class,'removeReaction'])->name('inbox.message.unreact');
 Route::get('/logs',[PanelController::class,'logs'])->name('logs');
 Route::get('/analytics',[AnalyticsController::class,'index'])->name('analytics');
 Route::get('/content',[ContentController::class,'index'])->name('content');
 Route::get('/content/create',[ContentController::class,'create'])->name('content.create');
 Route::post('/content/media/upload',[PanelController::class,'uploadContentMedia'])->name('content.media.upload');
 Route::post('/content',[ContentController::class,'store'])->name('content.store');
 Route::delete('/content',[ContentController::class,'destroy'])->name('content.destroy');
 Route::post('/content/story-insights',[ContentController::class,'storyInsights'])->name('content.story-insights');
 Route::get('/content/audio',[ContentController::class,'audio'])->name('content.audio');
 Route::post('/content/like',[ContentController::class,'like'])->name('content.like');
 Route::delete('/content/unlike',[ContentController::class,'unlike'])->name('content.unlike');
 Route::get('/content/timeline',[ContentController::class,'timeline'])->name('content.timeline');
 Route::get('/comments',[CommentsController::class,'index'])->name('comments');
 Route::get('/comments/list',[CommentsController::class,'list'])->name('comments.list');
 Route::post('/comments/reply',[CommentsController::class,'reply'])->name('comments.reply');
 Route::post('/comments/private-reply',[CommentsController::class,'privateReply'])->name('comments.private-reply');
 Route::delete('/comments/delete',[CommentsController::class,'delete'])->name('comments.delete');
 Route::post('/comments/hide',[CommentsController::class,'hide'])->name('comments.hide');
 Route::delete('/comments/unhide',[CommentsController::class,'unhide'])->name('comments.unhide');
 Route::post('/comments/like',[CommentsController::class,'like'])->name('comments.like');
 Route::delete('/comments/unlike',[CommentsController::class,'unlike'])->name('comments.unlike');
 Route::get('/settings',[PanelController::class,'settings'])->name('settings');
 Route::get('/settings/health',[PanelController::class,'accountHealth'])->name('settings.health');
 Route::post('/settings/ice-breakers',[PanelController::class,'iceBreakers'])->name('settings.ice-breakers');
 Route::post('/settings',[PanelController::class,'saveSettings'])->name('settings.save');
 Route::get('/notifications',[PanelController::class,'notifications'])->name('notifications');
 Route::get('/contacts',[OperationsController::class,'contacts'])->name('contacts');
 Route::get('/templates',[OperationsController::class,'templates'])->name('templates');
 Route::post('/templates',[OperationsController::class,'storeTemplate'])->name('templates.store');
 Route::post('/templates/{template}/toggle',[OperationsController::class,'toggleTemplate'])->name('templates.toggle');
 Route::delete('/templates/{template}',[OperationsController::class,'deleteTemplate'])->name('templates.destroy');
 Route::get('/media-library',[OperationsController::class,'media'])->name('media-library');
 Route::post('/media-library',[OperationsController::class,'storeMedia'])->name('media-library.store');
 Route::delete('/media-library/{media}',[OperationsController::class,'deleteMedia'])->name('media-library.destroy');
 Route::get('/system-health',[OperationsController::class,'health'])->name('system-health');
});
