@extends('layout')
@section('page_title','نظرات')
@section('page_hint','انتخاب پست، مشاهده نظرها و پاسخ سریع')
@section('content')
<div class="page-header-row"><div><div class="eyebrow">مدیریت جامعه</div><h1>نظرات</h1><p>یک محتوا را انتخاب کن و پاسخ‌ها، مخفی‌سازی، حذف و پسندیدن را همان‌جا مدیریت کن.</p></div><a class="soft-button" href="{{ route('automations.create') }}">ساخت اتوماسیون برای کامنت ↗</a></div>
<div class="comments-shell">
<aside class="comment-posts-panel"><div class="side-panel-head"><div><strong>محتوا</strong><small>برای مشاهده نظرها انتخاب کن</small></div><div class="select-shell compact"><select id="commentAccountSelect">@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($selectedAccount?->id===$account->id)>{{ '@'.($account->username ?: 'instagram') }}</option>@endforeach</select></div></div><div class="comment-post-list" id="commentPostList"><div class="empty-state"><div class="spinner"></div><strong>در حال بارگذاری محتوا</strong></div></div></aside>
<section class="comment-detail-panel"><div class="comment-detail-head"><div><div class="eyebrow">نظرها</div><h2 id="commentsTitle">یک محتوا را انتخاب کن</h2><p id="commentsSubtitle">نظرهای همان محتوا اینجا دیده می‌شوند.</p></div><div class="comment-search search-field"><span>⌕</span><input type="search" id="commentsSearch" placeholder="جست‌وجوی نظر…"></div></div><div class="comments-list" id="commentsList"><div class="empty-state"><div class="empty-icon">◎</div><strong>هنوز محتوایی انتخاب نشده</strong><p>از سمت راست یک کارت انتخاب کن.</p></div></div></section>
</div>
<div class="comment-modal" data-comment-reply-modal hidden><div class="comment-modal-card"><button class="modal-close" type="button" data-close-comment-modal>×</button><div class="eyebrow">پاسخ به نظر</div><h3 data-comment-reply-title>پاسخ</h3><div class="reply-mode-tabs"><button type="button" class="active" data-reply-mode="public">پاسخ عمومی</button><button type="button" data-reply-mode="private">پیام خصوصی</button></div><form id="commentReplyForm"><input type="hidden" id="replyAccountId"><input type="hidden" id="replyPostId"><input type="hidden" id="replyCommentId"><input type="hidden" id="replyMode" value="public"><textarea id="replyMessage" maxlength="2200" placeholder="پاسخ خود را بنویس…"></textarea><div class="reply-interactive" id="replyInteractive" hidden><div class="quick-interactive-row"><label>پاسخ‌های سریع</label><input id="replyQuickReplies" type="text" placeholder="مثلاً قیمت | سفارش | موجودی"></div><div class="quick-interactive-row"><label>دکمه‌ها</label><input id="replyButtons" type="text" placeholder="عنوان | لینک، عنوان دوم | لینک دوم"></div></div><input type="hidden" id="replyQuickJson"><input type="hidden" id="replyButtonsJson"><div class="modal-actions"><button type="button" class="secondary-action" data-close-comment-modal>انصراف</button><button type="submit" class="primary-action">ارسال پاسخ</button></div></form></div></div>
@endsection
