<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('contacts', function(Blueprint $t){$t->id();$t->foreignId('instagram_account_id')->nullable()->constrained()->nullOnDelete();$t->string('external_user_id')->nullable();$t->string('username')->nullable();$t->string('full_name')->nullable();$t->boolean('is_follower')->nullable();$t->unsignedBigInteger('follower_count')->nullable();$t->boolean('is_verified')->nullable();$t->string('state',30)->default('active');$t->boolean('needs_human')->default(false);$t->timestamp('last_seen_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['instagram_account_id','external_user_id']);});
  Schema::create('tags', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->string('slug')->unique();$t->string('color')->nullable();$t->timestamps();});
  Schema::create('contact_tag', function(Blueprint $t){$t->foreignId('contact_id')->constrained()->cascadeOnDelete();$t->foreignId('tag_id')->constrained()->cascadeOnDelete();$t->primary(['contact_id','tag_id']);});
  Schema::create('conversations', function(Blueprint $t){$t->id();$t->foreignId('instagram_account_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('contact_id')->nullable()->constrained()->nullOnDelete();$t->string('zernio_conversation_id')->unique();$t->string('status',30)->default('active');$t->boolean('needs_human')->default(false);$t->timestamp('last_message_at')->nullable();$t->timestamp('last_inbound_at')->nullable();$t->unsignedInteger('unread_count')->default(0);$t->json('metadata')->nullable();$t->timestamps();$t->index(['status','needs_human','last_message_at']);});
  Schema::create('messages', function(Blueprint $t){$t->id();$t->foreignId('conversation_id')->constrained()->cascadeOnDelete();$t->string('external_message_id')->nullable()->unique();$t->string('direction',20);$t->string('type',30)->default('text');$t->text('text')->nullable();$t->string('status',30)->nullable();$t->string('source',40)->nullable();$t->json('attachments')->nullable();$t->json('metadata')->nullable();$t->timestamp('sent_at')->nullable();$t->timestamps();$t->index(['conversation_id','created_at']);});
  Schema::create('automation_versions', function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('version');$t->string('label')->nullable();$t->json('snapshot');$t->foreignId('created_by')->nullable();$t->timestamps();$t->unique(['automation_id','version']);});
  Schema::create('automation_nodes', function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('node_key');$t->string('type',40);$t->string('label')->nullable();$t->unsignedInteger('position_x')->default(0);$t->unsignedInteger('position_y')->default(0);$t->json('config')->nullable();$t->timestamps();$t->unique(['automation_id','node_key']);});
  Schema::create('automation_edges', function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('source_key');$t->string('target_key');$t->string('condition')->nullable();$t->json('config')->nullable();$t->timestamps();$t->index(['automation_id','source_key']);});
  Schema::create('automation_runs', function(Blueprint $t){$t->id();$t->foreignId('automation_id')->constrained()->cascadeOnDelete();$t->string('event_id')->nullable()->index();$t->string('status',30)->default('running');$t->json('context')->nullable();$t->json('result')->nullable();$t->text('error')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->timestamps();$t->index(['automation_id','created_at']);});
  Schema::create('rate_limit_buckets', function(Blueprint $t){$t->id();$t->string('bucket_key')->unique();$t->unsignedInteger('hits')->default(0);$t->timestamp('window_started_at');$t->timestamps();});
  Schema::create('app_settings', function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->timestamps();});
  Schema::create('business_hours', function(Blueprint $t){$t->id();$t->unsignedTinyInteger('day_of_week');$t->time('opens_at')->nullable();$t->time('closes_at')->nullable();$t->boolean('enabled')->default(true);$t->timestamps();$t->unique('day_of_week');});
  Schema::create('notifications', function(Blueprint $t){$t->id();$t->string('type',40);$t->string('title');$t->text('body')->nullable();$t->boolean('read')->default(false);$t->json('data')->nullable();$t->timestamps();$t->index(['read','created_at']);});
  Schema::create('audit_logs', function(Blueprint $t){$t->id();$t->string('action');$t->string('entity_type')->nullable();$t->unsignedBigInteger('entity_id')->nullable();$t->string('ip_address')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->timestamps();$t->index(['entity_type','entity_id']);});
 }
 public function down(): void { foreach(['audit_logs','notifications','business_hours','app_settings','rate_limit_buckets','automation_runs','automation_edges','automation_nodes','automation_versions','messages','conversations','contact_tag','tags','contacts'] as $t) Schema::dropIfExists($t); }
};
