@extends('layout')
@section('page_title','تحلیل و آمار')
@section('page_hint','روند رشد، تعامل و رفتار مخاطبان را از یک صفحه ببین')
@section('content')
<div class="page-header-row"><div><div class="eyebrow">تحلیل</div><h1>تحلیل و آمار</h1><p>آمار حساب و روند دنبال‌کننده‌ها را در کنار عملکرد اتوماسیون‌ها بررسی کن.</p></div><div class="select-shell"><span>حساب</span><select onchange="window.location='{{ route('analytics') }}?account_id='+this.value">@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($selectedAccount?->id===$account->id)>{{ '@'.($account->username ?: 'instagram') }}</option>@endforeach</select></div></div>
@if(!empty($apiNotice))<div class="help-box">{{ $apiNotice }}</div>@endif
<div class="insight-grid insight-grid-large">
@foreach([['دسترسی',data_get($insights,'reach',data_get($insights,'data.reach',0)),'افرادی که محتوا به آن‌ها رسیده'],['بازدید',data_get($insights,'views',data_get($insights,'data.views',0)),'دفعات مشاهده'],['تعامل',data_get($insights,'accountsEngaged',data_get($insights,'data.accountsEngaged',0)),'حساب‌های درگیر'],['تعاملات',data_get($insights,'totalInteractions',data_get($insights,'data.totalInteractions',0)),'مجموع تعامل'],['دنبال‌کردن',data_get($insights,'follows',data_get($insights,'data.follows',0)),'دنبال‌کننده‌های جدید'],['لغو دنبال‌کردن',data_get($insights,'unfollows',data_get($insights,'data.unfollows',0)),'کاهش دنبال‌کننده']] as $stat)
<div class="insight-box premium-insight"><span>{{ $stat[0] }}</span><strong>{{ is_numeric($stat[1])?number_format((float)$stat[1]):'—' }}</strong><p>{{ $stat[2] }}</p></div>
@endforeach
</div>
<div class="analytics-grid-pro"><section class="panel-card"><div class="section-head"><div><div class="eyebrow">روند رشد</div><h2>دنبال‌کننده‌ها</h2></div><span class="soft-tag">{{ count($followers ?? []) }} نقطه</span></div><div class="chart-pro analytics-chart">@php($max=max(1,collect($followers ?? [])->max(fn($x)=>(float)data_get($x,'followers',data_get($x,'followerCount',0)))))@forelse($followers as $item)<div class="chart-col"><span class="chart-value">{{ number_format((float)data_get($item,'followers',data_get($item,'followerCount',0))) }}</span><div class="chart-bar-wrap"><div class="chart-bar" style="height:{{ min(100,max(8,((float)data_get($item,'followers',data_get($item,'followerCount',0))/$max)*100)) }}%"></div></div><span>{{ Str::limit((string)data_get($item,'date',data_get($item,'timestamp','')),7,'') }}</span></div>@empty<div class="empty-state span-full"><strong>داده روند موجود نیست</strong></div>@endforelse</div></section>
<section class="panel-card"><div class="section-head"><div><div class="eyebrow">مخاطبان</div><h2>جمعیت‌شناسی</h2></div><span class="soft-tag">اختیاری</span></div><div class="demographics-grid">@foreach(['country'=>'کشور','city'=>'شهر','age'=>'سن','gender'=>'جنسیت'] as $key=>$label)<div class="demo-card"><strong>{{ $label }}</strong>@php($rows=data_get($demographics,$key, data_get($demographics,'data.'.$key,[])))<div class="demo-list">@forelse(is_array($rows)?$rows:[] as $row)<div><span>{{ $row['label'] ?? $row['name'] ?? $row['value'] ?? '—' }}</span><b>{{ $row['value'] ?? $row['count'] ?? $row['percentage'] ?? 0 }}</b></div>@empty<span class="muted">داده‌ای برای نمایش نیست.</span>@endforelse</div></div>@endforeach</div></section></div>
@endsection
