@extends('layout')
@section('page_title','تنظیمات')
@section('page_hint','اتصال حساب، ساعات کاری و رفتار کلی سیستم را مدیریت کن')
@section('content')
<div class="page-header-row"><div><div class="eyebrow">تنظیمات</div><h1>تنظیمات مرکز مدیریت</h1><p>تنظیمات عمومی را یک‌بار مشخص کن تا اتوماسیون‌ها از همان الگو استفاده کنند.</p></div></div>
<div class="settings-grid settings-grid-pro">
<div class="settings-main">
<section class="editor-card settings-card-highlight"><div class="section-head"><div><div class="eyebrow">کنترل اصلی</div><h2>کل سیستم</h2><p>در صورت نیاز، همه پاسخ‌های خودکار را با یک سوییچ متوقف کن.</p></div><span class="master-state {{ $globalEnabled?'on':'off' }}">{{ $globalEnabled?'فعال':'متوقف' }}</span></div><form method="POST" action="{{ route('settings.save') }}">@csrf<input type="hidden" name="global_enabled" value="0"><label class="master-toggle"><span class="master-icon">⚡</span><div><strong>اجرای اتوماسیون‌ها</strong><small>وقتی خاموش باشد، رویدادها ثبت می‌شوند ولی پاسخ خودکار ارسال نمی‌شود.</small></div><input class="toggle-input" type="checkbox" name="global_enabled" value="1" @checked($globalEnabled)><span class="toggle-ui"></span></label>
<div class="setting-divider"></div><label class="master-toggle"><span class="master-icon">◷</span><div><strong>ساعات کاری</strong><small>اتوماسیون‌هایی که به این محدودیت وابسته‌اند فقط در این ساعات اجرا می‌شوند.</small></div><input class="toggle-input" type="checkbox" name="hours_enabled" value="1" @checked($hoursEnabled)><span class="toggle-ui"></span></label>
<div class="hours-table"><div class="hours-head"><span>روز</span><span>فعال</span><span>شروع</span><span>پایان</span></div>@php($days=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'])@foreach($days as $i=>$day)<div class="hours-row"><strong>{{ $day }}</strong><label class="mini-check"><input type="checkbox" name="day_{{ $i }}" value="1" @checked(data_get($businessHours,$i.'.enabled',true))><span></span></label><input type="time" name="from_{{ $i }}" value="{{ data_get($businessHours,$i.'.from','09:00') }}"><input type="time" name="to_{{ $i }}" value="{{ data_get($businessHours,$i.'.to','18:00') }}"></div>@endforeach</div>
<div class="save-dock-actions"><button class="primary-action" type="submit">✓ ذخیره تنظیمات</button></div></form></section>

<section class="editor-card"><div class="section-head"><div><div class="eyebrow">شروع گفتگو</div><h2>پرسش‌های آغازین</h2><p>حداکثر ۴ پرسش کوتاه که هنگام شروع یک گفتگوی جدید نمایش داده می‌شوند.</p></div><span class="soft-tag">حداکثر ۸۰ نویسه برای هر مورد</span></div><form method="POST" action="{{ route('settings.ice-breakers') }}">@csrf<input type="hidden" name="account_id" value="{{ $selectedAccount?->id }}"><div class="icebreaker-grid">@for($i=0;$i<4;$i++)<div class="icebreaker-item"><span>{{ $i+1 }}</span><input name="items[]" maxlength="80" value="{{ data_get($iceBreakers,$i.'.question', data_get($iceBreakers,$i.'.text','')) }}" placeholder="مثلاً قیمت این محصول چقدر است؟"></div>@endfor</div><div class="save-dock-actions"><button class="secondary-action" type="submit">ذخیره پرسش‌ها</button></div></form></section>
</div>
<aside class="settings-side sticky-side"><section class="editor-card"><div class="section-head"><div><div class="eyebrow">حساب فعال</div><h2>{{ $selectedAccount?->username ? '@'.$selectedAccount->username : 'حسابی انتخاب نشده' }}</h2></div><span class="status-badge {{ $selectedAccount?'active':'paused' }}"><i></i>{{ $selectedAccount?'متصل':'نیازمند بررسی' }}</span></div><div class="health-list">@foreach([['توکن',data_get($health,'tokenStatus.valid')===true?'معتبر':(data_get($health,'tokenStatus.valid')===false?'نامعتبر':'نامشخص')],['وضعیت اتصال',data_get($health,'summary.status',data_get($health,'status','نامشخص'))],['مجوزها',data_get($health,'permissions.ok')===true?'معتبر':'بررسی شود'],['اتصال مجدد',data_get($health,'summary.needsReconnect')===true?'لازم است':'لازم نیست']] as $row)<div><span>{{ $row[0] }}</span><strong>{{ $row[1] }}</strong></div>@endforeach</div><button type="button" class="secondary-action full-width" data-health-check data-url="{{ route('settings.health',['account_id'=>$selectedAccount?->id]) }}">بررسی دوباره</button></section>
<section class="editor-card"><div class="section-head"><div><div class="eyebrow">Webhook</div><h2>آدرس رویداد ورودی</h2></div><span class="soft-tag green">فعال</span></div><div class="copy-field"><input readonly value="{{ url('/api/webhooks/inbound') }}" id="webhookUrl"><button type="button" class="secondary-action" data-copy-target="#webhookUrl">کپی</button></div><small class="field-note">این آدرس برای دریافت رویدادهای ورودی استفاده می‌شود. کلید امضا فقط روی سرور نگهداری می‌شود.</small></section>
<section class="editor-card"><div class="section-head"><div><div class="eyebrow">حساب‌ها</div><h2>حساب‌های فعال</h2></div></div><div class="accounts-side-list">@forelse($accounts as $account)<div><div class="account-avatar small">{{ mb_strtoupper(mb_substr($account->username ?: 'IG',0,2)) }}</div><div><strong>{{ '@'.($account->username ?: 'instagram') }}</strong><small>{{ $account->name ?: 'حساب اینستاگرام' }}</small></div><span class="online-dot"></span></div>@empty<div class="empty-mini">حساب فعالی ثبت نشده است.</div>@endforelse</div></section></aside>
</div>
@endsection
